### PR TITLE
Issue #1306 mitigate replay modified jwt passport

### PR DESCRIPTION
**Pull request by christian-hawk**
Related to #1306 

I was able to reproduce, and now the script blocks **none attacks** on the passport-saml side.

I changed `.getSigningAlgorithm` (was not working in my server) to `.getAlgorithm()` method (please see comments).

I also left the `customScript` arg  at `PersonAuthenticator` arg (need to remove to work on my version)

### CODE REVIEW

File: Server/integrations/saml-passport/SamlPassportAuthenticator.py [hunk 1]
```diff
@@ -438,19 +485,48 @@ def validSignature(self, jwt):
...
+            elif signature_string == "" :
+                # blocks empty signature string
+                print "WARNING: JWT Signature not sent"
+                valid = False
+            
+            else:
+                #changed method from .getSignatureAlgorithm() to getAlgorithm()
+                # class that extends AbstractCryptoProvider
+                
+                valid = cryptoProvider.verifySignature(jwt.getSigningInput(), jwt.getEncodedSignature(), jwt.getHeader().getKeyId(),
```
Comment (yuriyz) [inline Server/integrations/saml-passport/SamlPassportAuthenticator.py:522]: It's not clear how it should work since verifySignature method has SignatureAlgorithm in that method, see
https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/gluu/oxauth/model/crypto/OxAuthCryptoProvider.java#L263

It seems it should be `jwt.getHeader().getSignatureAlgorithm()`.
Did you test it?

Comment (christian-hawk) [reply Server/integrations/saml-passport/SamlPassportAuthenticator.py:522]: Hello @yuriyz ! Thx for checking. Yes I tested.

- `jwt.getHeader().getSignatureAlgorithm()` does not work on my gluu 4.1.1 (updated identity jar)
- `jwt.getHeader().getAlgorithm()` works and returns `alg` header field. 
- 

Just in case I gonna take some time right now to investigate a little further the non-working `getSignatureAlgorithm()` on my side, it was one of the first things I changed so I will refresh my memory and get back to you.

Comment (yuriyz) [reply Server/integrations/saml-passport/SamlPassportAuthenticator.py:522]: This PR is to master. If you follow link I posted above you will see that in master verifySignature accepts SignatureAlgorithm. Thus it is not clear how it is going to work on master (4.2).

Comment (christian-hawk) [reply Server/integrations/saml-passport/SamlPassportAuthenticator.py:523]: Hello @yuriyz .
On my version without `customScript` as `PersonAuthentication` arg that [you can check in this commit](https://github.com/GluuFederation/oxAuth/commit/9f053092a3eeaa324444b796bb1ddb22fa42e506) i get:

```
2020-05-14 16:24:57,116 INFO  [qtp1590550415-62] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:240) - Exception: 
2020-05-14 16:24:57,117 INFO  [qtp1590550415-62] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:240) -  'org.gluu.oxauth.model.jwt.JwtHeader' object has no attribute 'getSignatureAlgorithm'
```

Comment (christian-hawk) [reply Server/integrations/saml-passport/SamlPassportAuthenticator.py:523]: > This PR is to master. If you follow link I posted above you will see that in master verifySignature accepts SignatureAlgorithm. Thus it is not clear how it is going to work on master (4.2).

Sorry conversation wasn't updated...  checking.

Comment (yuriyz) [reply Server/integrations/saml-passport/SamlPassportAuthenticator.py:523]: Here is diff of `JwtHeader` between 4.1 and master. So yes, in 4.1 it's `getAlgorithm()` but in master (4.2) it's `getSignatureAlgorithm()`. This PR is opened on master.

image

Comment (christian-hawk) [reply Server/integrations/saml-passport/SamlPassportAuthenticator.py:521]: thanks! changed.
